# A Helm Chart for an IOC instance
apiVersion: v2
name: ec-service
version: 1.0.0

type: application

dependencies:
  - name: ioc-instance
    version: 5.0.0-beta.1
    repository: "oci://ghcr.io/epics-containers/charts"
